import "../public/css/globals.css";
import Header from "../components/Header/Header";
import Footer from "../components/Footer/Footer"
import { Inter } from 'next/font/google'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
})


export const metadata = {
  title: "JobIn",
  description: "Generated by create next app",
  icons: {
    icon: '/img/global/favicon.svg'
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={inter.variable}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
