import "../public/css/globals.css";
import Header from "../components/Header/Header";
import Footer from "../components/Footer/Footer"

export const metadata = {
  title: "JobIn",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
